-- MySQL Script generated by MySQL Workbench
-- Fri 13 Feb 2026 02:41:42 PM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tokolistrik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tokolistrik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tokolistrik` ;
USE `tokolistrik` ;

-- -----------------------------------------------------
-- Table `tokolistrik`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `deleted_at` VARCHAR(45) NULL,
  `categories_id` INT NOT NULL,
  `photo` VARCHAR(255) NULL,
  `has_variant` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) ,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `tokolistrik`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL DEFAULT current_timestamp,
  `total` INT NOT NULL,
  `shipping` VARCHAR(45) NULL,
  `shipping_fee` INT NOT NULL DEFAULT 0,
  `payment_methods` ENUM('tunai', 'transfer', 'piutang') NOT NULL,
  `total_debt` DOUBLE NOT NULL DEFAULT 0,
  `sales_type` VARCHAR(45) NOT NULL,
  `discount` INT NULL,
  `discount_type` VARCHAR(45) NULL,
  `customers_id` INT NULL,
  `tax` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_customers1_idx` (`customers_id` ASC) ,
  CONSTRAINT `fk_sales_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `tokolistrik`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`variants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `products_id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variants_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_variants_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`sales_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`sales_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sales_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL,
  `final_discount` INT NULL DEFAULT 0,
  `discount` INT NOT NULL DEFAULT 0,
  `discount_type` VARCHAR(45) NULL,
  `total_return` INT NOT NULL DEFAULT 0,
  `bonus` TINYINT NOT NULL DEFAULT 0,
  `variants_id` INT NULL,
  PRIMARY KEY (`id`, `sales_id`, `products_id`),
  INDEX `fk_sales_has_products_products1_idx` (`products_id` ASC) ,
  INDEX `fk_sales_has_products_sales1_idx` (`sales_id` ASC) ,
  INDEX `fk_sales_details_variants1_idx` (`variants_id` ASC) ,
  CONSTRAINT `fk_sales_has_products_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `tokolistrik`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_details_variants1`
    FOREIGN KEY (`variants_id`)
    REFERENCES `tokolistrik`.`variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suppliers_id` INT NOT NULL,
  `total` INT NOT NULL,
  `date` DATE NOT NULL DEFAULT current_timestamp,
  `discount` INT NOT NULL DEFAULT 0,
  `shipping` VARCHAR(45) NULL,
  `shipping_fee` INT NULL DEFAULT 0,
  `total_debt` INT NULL DEFAULT 0,
  `payment_methods` ENUM('tunai', 'transfer', 'hutang') NULL,
  `tax` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_supplier1_idx` (`suppliers_id` ASC) ,
  CONSTRAINT `fk_purchase_supplier1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `tokolistrik`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`purchase_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`purchase_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchases_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL,
  `total_return` VARCHAR(45) NOT NULL DEFAULT 0,
  `variants_id` INT NULL,
  PRIMARY KEY (`id`, `purchases_id`, `products_id`),
  INDEX `fk_purchase_has_products_products1_idx` (`products_id` ASC) ,
  INDEX `fk_purchase_has_products_purchase1_idx` (`purchases_id` ASC) ,
  INDEX `fk_purchase_details_variants1_idx` (`variants_id` ASC) ,
  CONSTRAINT `fk_purchase_has_products_purchase1`
    FOREIGN KEY (`purchases_id`)
    REFERENCES `tokolistrik`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_details_variants1`
    FOREIGN KEY (`variants_id`)
    REFERENCES `tokolistrik`.`variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`variants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `products_id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variants_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_variants_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`features` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mandatory` TINYINT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `route` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`sub_features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`sub_features` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mandatory` TINYINT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `type` ENUM('or', 'xor') NULL,
  `features_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sub_features_features1_idx` (`features_id` ASC) ,
  CONSTRAINT `fk_sub_features_features1`
    FOREIGN KEY (`features_id`)
    REFERENCES `tokolistrik`.`features` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mandatory` TINYINT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `type` ENUM('or', 'xor') NULL,
  `sub_features_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_configurations_sub_features1_idx` (`sub_features_id` ASC) ,
  CONSTRAINT `fk_configurations_sub_features1`
    FOREIGN KEY (`sub_features_id`)
    REFERENCES `tokolistrik`.`sub_features` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`detail_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`detail_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `mandatory` TINYINT NULL,
  `is_active` TINYINT NULL,
  `configurations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detail_configurations_configurations1_idx` (`configurations_id` ASC) ,
  CONSTRAINT `fk_detail_configurations_configurations1`
    FOREIGN KEY (`configurations_id`)
    REFERENCES `tokolistrik`.`configurations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`discount_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`discount_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `minimum` INT NULL DEFAULT 0,
  `bonus_quantity` INT NULL,
  `bonus_minimum` INT NULL,
  `products_id` INT NULL,
  `categories_id` INT NULL,
  `products_id1` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discount_rules_products1_idx` (`products_id` ASC) ,
  INDEX `fk_discount_rules_categories1_idx` (`categories_id` ASC) ,
  UNIQUE INDEX `categories_id_UNIQUE` (`categories_id` ASC) ,
  UNIQUE INDEX `products_id_UNIQUE` (`products_id` ASC) ,
  INDEX `fk_discount_rules_products2_idx` (`products_id1` ASC) ,
  CONSTRAINT `fk_discount_rules_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount_rules_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `tokolistrik`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount_rules_products2`
    FOREIGN KEY (`products_id1`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`debts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`debts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sales_id` INT NULL,
  `purchases_id` INT NULL,
  `paid` INT NOT NULL,
  `date` DATE NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_debts_sales1_idx` (`sales_id` ASC) ,
  INDEX `fk_debts_purchases1_idx` (`purchases_id` ASC) ,
  CONSTRAINT `fk_debts_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `tokolistrik`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debts_purchases1`
    FOREIGN KEY (`purchases_id`)
    REFERENCES `tokolistrik`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`discounted_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`discounted_products` (
  `products_id` INT NOT NULL,
  `discounts_rules_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `discounts_rules_id`),
  INDEX `fk_products_has_discounts_rules_discounts_rules1_idx` (`discounts_rules_id` ASC) ,
  INDEX `fk_products_has_discounts_rules_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_products_has_discounts_rules_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_discounts_rules_discounts_rules1`
    FOREIGN KEY (`discounts_rules_id`)
    REFERENCES `tokolistrik`.`discount_rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`discounted_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`discounted_categories` (
  `categories_id` INT NOT NULL,
  `discount_rules_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `discount_rules_id`),
  INDEX `fk_categories_has_discounts_rules_discounts_rules1_idx` (`discount_rules_id` ASC) ,
  INDEX `fk_categories_has_discounts_rules_categories1_idx` (`categories_id` ASC) ,
  CONSTRAINT `fk_categories_has_discounts_rules_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `tokolistrik`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_discounts_rules_discounts_rules1`
    FOREIGN KEY (`discount_rules_id`)
    REFERENCES `tokolistrik`.`discount_rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`product_returns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`product_returns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT current_timestamp,
  `amount` INT NULL,
  `type` VARCHAR(45) NULL,
  `sales_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `variants_id` INT NULL,
  `keterangan` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_returns_sales1_idx` (`sales_id` ASC) ,
  INDEX `fk_product_returns_products1_idx` (`products_id` ASC) ,
  INDEX `fk_product_returns_variants1_idx` (`variants_id` ASC) ,
  CONSTRAINT `fk_product_returns_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `tokolistrik`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_returns_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_returns_variants1`
    FOREIGN KEY (`variants_id`)
    REFERENCES `tokolistrik`.`variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`discounted_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`discounted_products` (
  `products_id` INT NOT NULL,
  `discounts_rules_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `discounts_rules_id`),
  INDEX `fk_products_has_discounts_rules_discounts_rules1_idx` (`discounts_rules_id` ASC) ,
  INDEX `fk_products_has_discounts_rules_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_products_has_discounts_rules_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_discounts_rules_discounts_rules1`
    FOREIGN KEY (`discounts_rules_id`)
    REFERENCES `tokolistrik`.`discount_rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokolistrik`.`purchase_returns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokolistrik`.`purchase_returns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT current_timestamp,
  `amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `purchases_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `variants_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_returns_purchases1_idx` (`purchases_id` ASC) ,
  INDEX `fk_purchase_returns_products1_idx` (`products_id` ASC) ,
  INDEX `fk_purchase_returns_variants1_idx` (`variants_id` ASC) ,
  CONSTRAINT `fk_purchase_returns_purchases1`
    FOREIGN KEY (`purchases_id`)
    REFERENCES `tokolistrik`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_returns_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tokolistrik`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_returns_variants1`
    FOREIGN KEY (`variants_id`)
    REFERENCES `tokolistrik`.`variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
